#' AI-Generated Institutional Report -- UI
#'
#' Produces a `nav_panel` containing a card with:
#' - A "Generate Report" action button
#' - A streaming text output area (updates progressively as tokens arrive)
#' - A disclaimer notice
#' - A download button for the Word document (enabled after generation)
#'
#' @param id Shiny module namespace ID.
#' @return A [bslib::nav_panel()] object.
#' @export
mod_report_ui <- function(id) {
  ns <- shiny::NS(id)

  bslib::nav_panel(
    title = "AI Report",
    value = "report",

    bslib::card(
      bslib::card_header(
        shiny::tagList(
          "AI-Generated Institutional Chapter",
          bslib::tooltip(
            bsicons::bs_icon("info-circle"),
            paste0(
              "Generates a draft governance chapter for the Country Growth and ",
              "Jobs Report using the CGJR Guidance Note framework. ",
              "The text is produced by a large language model and must be ",
              "reviewed and edited before any official use."
            ),
            placement = "right"
          )
        )
      ),

      # Controls row
      shiny::fluidRow(
        shiny::column(
          width = 9,
          bslib::input_task_button(
            id    = ns("generate"),
            label = "Generate Report",
            icon  = bsicons::bs_icon("robot"),
            type  = "primary"
          ),
          shiny::downloadButton(
            outputId = ns("download_docx"),
            label    = "Download Word",
            icon     = shiny::icon("file-word"),
            style    = "margin-left: 8px;"
          )
        ),
        shiny::column(
          width = 3,
          shiny::uiOutput(ns("status_badge"))
        )
      ),

      shiny::hr(),

      # Disclaimer
      bslib::card(
        class = "border-warning bg-warning-subtle mb-3",
        bslib::card_body(
          shiny::tags$small(
            shiny::tags$strong("Disclaimer: "),
            paste0(
              "This text is generated by a large language model based on ",
              "Closeness-to-Frontier scores. It is a draft starting point only ",
              "and must be reviewed and verified before use in any official document."
            )
          )
        )
      ),

      # Streaming output
      shiny::uiOutput(ns("report_output"))
    )
  )
}


#' AI-Generated Institutional Report -- Server
#'
#' Handles the report generation workflow: builds the prompt, streams the LLM
#' response token-by-token into a reactive value, renders the accumulated text
#' as Markdown HTML, and provides a Word download.
#'
#' @param id Shiny module namespace ID.
#' @param primary_iso Reactive returning the primary country ISO3 code.
#' @param peer_isos Reactive returning a character vector of peer ISO3 codes.
#' @param region_codes Reactive returning a character vector of region codes.
#' @param income_groups Reactive returning a character vector of income group
#'   labels.
#' @param year_range Reactive returning an integer vector of length 2:
#'   `c(min_year, max_year)`.
#'
#' @return Called for side effects; returns `NULL` invisibly.
#' @export
mod_report_server <- function(id, primary_iso, peer_isos,
                               region_codes, income_groups, year_range) {
  shiny::moduleServer(id, function(input, output, session) {

    # Reactive accumulator for streamed tokens
    r_report_text   <- shiny::reactiveVal("")
    r_is_generating <- shiny::reactiveVal(FALSE)
    r_is_done       <- shiny::reactiveVal(FALSE)
    r_error_msg     <- shiny::reactiveVal(NULL)

    # ── Status badge ──────────────────────────────────────────────────────────
    output$status_badge <- shiny::renderUI({
      if (isTRUE(r_is_generating())) {
        shiny::tags$span(class = "badge bg-secondary", "Generating...")
      } else if (!is.null(r_error_msg())) {
        shiny::tags$span(class = "badge bg-danger", "Error")
      } else if (isTRUE(r_is_done()) && nchar(r_report_text()) > 0L) {
        shiny::tags$span(class = "badge bg-success", "Ready")
      } else {
        shiny::tags$span(class = "badge bg-light text-dark", "Not yet generated")
      }
    })

    # ── Report streaming output ───────────────────────────────────────────────
    output$report_output <- shiny::renderUI({
      text <- r_report_text()
      err  <- r_error_msg()

      if (!is.null(err)) {
        bslib::card(
          class = "border-danger",
          bslib::card_body(
            shiny::tags$p(
              class = "text-danger",
              shiny::tags$strong("Error: "),
              err
            )
          )
        )
      } else if (nchar(text) == 0L) {
        shiny::tags$p(
          class = "text-muted",
          "Click 'Generate Report' to produce a draft institutional chapter ",
          "for the selected country."
        )
      } else {
        shiny::tagList(
          shiny::HTML(commonmark::markdown_html(text)),
          if (isTRUE(r_is_generating())) {
            shiny::tags$span(
              class = "spinner-grow spinner-grow-sm text-secondary ms-2",
              role  = "status",
              shiny::tags$span(class = "visually-hidden", "Generating...")
            )
          }
        )
      }
    })

    # ── Generate button handler ───────────────────────────────────────────────
    shiny::observeEvent(input$generate, {
      shiny::req(primary_iso())

      # Reset state
      r_report_text("")
      r_is_generating(TRUE)
      r_is_done(FALSE)
      r_error_msg(NULL)

      iso    <- primary_iso()
      peers  <- peer_isos()
      regs   <- region_codes()
      incs   <- income_groups()
      yr     <- year_range()

      # Resolve display name
      country_name <- tryCatch(
        cgjrdata::wbcountries |>
          dplyr::filter(country_code == iso) |>
          dplyr::pull(economy) |>
          dplyr::first(),
        error = function(e) iso
      )

      # Check LLM availability first
      if (!check_llm_available()) {
        r_error_msg(
          paste0(
            "Cannot reach the LLM endpoint. ",
            "Check that CGJR_LLM_BASE_URL, CGJR_LLM_MODEL, and ",
            "CGJR_LLM_API_KEY are set correctly in your .Renviron."
          )
        )
        r_is_generating(FALSE)
        return()
      }

      # Build scores data for the prompt
      scores_tbl <- tryCatch(
        get_scores_table(iso, peers, regs, incs, yr),
        error = function(e) NULL
      )

      if (is.null(scores_tbl) || nrow(scores_tbl) == 0L) {
        r_error_msg("Could not retrieve scores data. Please try again.")
        r_is_generating(FALSE)
        return()
      }

      # Build prompt
      user_prompt <- tryCatch(
        build_cgjr_prompt(
          primary_iso   = iso,
          primary_name  = country_name,
          scores_tbl    = scores_tbl,
          year_range    = yr,
          peer_isos     = peers,
          region_codes  = regs,
          income_groups = incs
        ),
        error = function(e) NULL
      )

      if (is.null(user_prompt)) {
        r_error_msg("Failed to build the report prompt.")
        r_is_generating(FALSE)
        return()
      }

      # Stream in a future so the UI remains responsive
      shiny::withProgress(
        message = paste0("Generating report for ", country_name, "..."),
        value   = 0,
        {
          tryCatch(
            stream_llm_response(
              prompt       = user_prompt,
              reactive_val = r_report_text,
              on_complete  = function(text) {
                r_is_generating(FALSE)
                r_is_done(TRUE)
              }
            ),
            error = function(e) {
              r_error_msg(conditionMessage(e))
              r_is_generating(FALSE)
            }
          )
        }
      )
    })

    # ── Word download ─────────────────────────────────────────────────────────
    output$download_docx <- shiny::downloadHandler(
      filename = function() {
        iso <- primary_iso()
        paste0("CGJR_Institutional_Report_", iso, "_",
               format(Sys.Date(), "%Y%m%d"), ".docx")
      },
      content = function(file) {
        text <- r_report_text()
        shiny::req(nchar(text) > 0L)

        iso <- primary_iso()
        country_name <- tryCatch(
          cgjrdata::wbcountries |>
            dplyr::filter(country_code == iso) |>
            dplyr::pull(economy) |>
            dplyr::first(),
          error = function(e) iso
        )

        doc <- format_report_docx(
          report_text  = text,
          country_name = country_name
        )
        print(doc, target = file)
      }
    )
  })
}
